from typing import Optional
from utils_inne.make_ksef_model_with_extras import make_ksef_model_with_extras

FaWiersz = make_ksef_model_with_extras(
    "FaWiersz",
    fields={
        "NrWierszaFa": "TNaturalny",
        "UU_ID": Optional["TZnakowy50"],
        "P_6A": Optional["TDataT"],
        "P_7": Optional["TZnakowy512"],
        "Indeks": Optional["TZnakowy50"],
        "GTIN": Optional["TZnakowy20"],
        "PKWiU": Optional["TZnakowy50"],
        "CN": Optional["TZnakowy50"],
        "PKOB": Optional["TZnakowy50"],
        "P_8A": Optional["TZnakowy"],
        "P_8B": Optional["TIlosci"],
        "P_9A": Optional["TKwotowy2"],
        "P_9B": Optional["TKwotowy2"],
        "P_10": Optional["TKwotowy2"],
        "P_11": Optional["TKwotowy"],
        "P_11A": Optional["TKwotowy"],
        "P_11Vat": Optional["TKwotowy"],
        "P_12": Optional["TStawkaPodatku"],
        "P_12_XII": Optional["TProcentowy"],
        "P_12_Zal_15": Optional["TWybor1"],
        "KwotaAkcyzy": Optional["TKwotowy"],
        "GTU": Optional["TGTU"],
        "Procedura": Optional["TOznaczenieProcedury"],
        "KursWaluty": Optional["TIlosci"],
        "StanPrzed": Optional["TWybor1"],
    },
    field_extras={
        "NrWierszaFa": {"title": "Numer wiersza faktury", "order": 1},
        "UU_ID": {"title": "Unikalny identyfikator wiersza (UUID)", "order": 2},
        "P_6A": {"title": "Data dokonania dostawy / zakończenia usługi", "order": 3},
        "P_7": {"title": "Nazwa (rodzaj) towaru lub usługi", "order": 4},
        "Indeks": {"title": "Indeks wewnętrzny towaru/usługi", "order": 5},
        "GTIN": {"title": "Kod GTIN (np. EAN)", "order": 6},
        "PKWiU": {"title": "Symbol PKWiU", "order": 7},
        "CN": {"title": "Kod Nomenklatury Scalonej (CN)", "order": 8},
        "PKOB": {"title": "Symbol PKOB", "order": 9},
        "P_8A": {"title": "Jednostka miary", "order": 10},
        "P_8B": {"title": "Ilość", "order": 11},
        "P_9A": {"title": "Cena jednostkowa netto", "order": 12},
        "P_9B": {"title": "Cena jednostkowa brutto (dla faktur brutto)", "order": 13},
        "P_10": {"title": "Kwota opustu lub obniżki ceny", "order": 14},
        "P_11": {"title": "Wartość sprzedaży netto", "order": 15},
        "P_11A": {"title": "Wartość sprzedaży brutto", "order": 16},
        "P_11Vat": {"title": "Kwota podatku VAT dla wiersza", "order": 17},
        "P_12": {"title": "Stawka podatku", "order": 18},
        "P_12_XII": {"title": "Stawka ryczałtu (jeśli dotyczy)", "order": 19},
        "P_12_Zal_15": {"title": "Obowiązek stosowania MPP (art. 108a ust. 1a)", "order": 20},
        "KwotaAkcyzy": {"title": "Kwota akcyzy zawarta w cenie", "order": 21},
        "GTU": {"title": "Oznaczenie GTU", "order": 22},
        "Procedura": {"title": "Procedury szczególne dla wiersza", "order": 23},
        "KursWaluty": {"title": "Kurs waluty (jeśli inny niż dla faktury)", "order": 24},
        "StanPrzed": {"title": "Stan przed korektą (dla faktur korygujących)", "order": 25},
    }
)